### ISSUE TITLE
Failed initialize the object

### ISSUE THREAD

**Issue by frothmoon** [bukalapak/pybrisque#8]
I successfully installed libsvm and pybrisque ,but I cannot initialize the BRISQUE.
```
$ python
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybirsque
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pybirsque'
>>> import pybrisque
>>> brisq = BRISQUE()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'BRISQUE' is not defined
>>> brisq = pybrisque.BRISQUE()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pybrisque' has no attribute 'BRISQUE'
>>> 
```

Are there anything wrong with using the  implement？

Thank you for your help！

**Comment by adzil** [comment]
You should import `brisque` instead of `pybrisque`.

```
from brisque import BRISQUE

brisq = BRISQUE()
```
